### PR TITLE
fixes for subtypes and second subtypes

### PR DESCRIPTION
**Pull request by jenlindner**
Hi @awead -- this still needs a little cleanup (some contexts in the feature tests need it blocks or to be commented out, for example), but I wanted to get it out there and reviewed by @scossu and at least checked out by you now. Not the best js in the word but it is fixing the bugs.

### CODE REVIEW

**Comment by jenlindner** [comment]
Ugh, @awead, we're getting errors in the feature tests from travis that I just don't get locally, and one even from a test that shouldn't have been affected. Should I try to recreate them locally, or do you have a silver bullet? Might be that I'm not using Capybara helper methods where I ought to be (though I thought I was), and therefore causing timing problems.

**Comment by awead** [comment]
@jenlindner try running it locally with the same seed. There could be an issue with stray assets in Solr and Fedora because tests are randomized. I would also try to run as many tests within one page load.

**Comment by jenlindner** [comment]
I decided a new strategy is a good idea. Now I'm only testing the user flow that had exposed the bugs the js (and back end persistence) changes fix in one new feature spec. But still seeing test problems with Travis that I don't get locally, with the same seeds. 

I'll keep thinking about what might be causing this and what to do about it.

**Comment by jenlindner** [comment]
And now I don't know *what* to think about the build passing.

**Pull request closed without merging**
