### PR TITLE
Assign correct value to citi_uid, fixes #599

### PR DESCRIPTION
**Pull request by scossu**

### CODE REVIEW

**Comment by awead** [comment]
@scossu the merge branch commit shouldn't be there. I think it might be easier to work on a topic branch in your fork, or just don't use the fork.
ex. in a fork:

```
git checkout develop
git remote add upstream https://github.com/aic-collections/aicdams-lakeshore
git fetch upstream
git merge upstream/develop
git checkout -b 599-fix
#do the work, then commit
git push origin 599-fix
```

Then, issue a PR to merge scossu:599-fix into aic-collections:develop. The idea with the fork is that scossu:develop is always in sync with aic-collections:develop and you do your work by checking out branches off of develop and rebase from develop as needed whenever you re-fetch from upstream.

However, since you have full rights to aic-collections, I would just push the 599-fix branch to here, and issue the PR to merge aic-collections:599-fix into aic-collections:develop. You'd still need to rebase off of develop if I push new changes, but you don't have to futz with the upstream fetching.

**Comment by scossu** [comment]
Got it. I will yank this PR  off and open another one.  I prefer going through PRs so you can review and comment on the changes.

**Comment by awead** [comment]
👍

**Comment by awead** [comment]
@scossu thanks, yes, PRs are the way to go, even for small changes.

**Pull request closed without merging**
