### PR TITLE
2386: API does not respect duplicate_check parameter

### PR DESCRIPTION
**Pull request by kefo**
Redmine issue https://cits.artic.edu/redmine/issues/2386.

### CODE REVIEW

**Comment by awead** [comment]
@kefo @RudyOnRails if you run `bundle exec rubocop -a` it'll fix the errors for you.

**Comment by kefo** [comment]
Thanks @awead .  You mentioned that last time and I looked it up yesterday and ran precisely that command.  Doesn't mean I don't think Rubocop is a tool.  Pun intended. :)

**Comment by kefo** [comment]
In other news, I'm not sure why coveralls failed.  If it is something I need to attend to, get me pointed in the right direction.

**Comment by RudyOnRails** [comment]
Nah you're good. Coveralls is just complaining that the percentage of
coverage decreased. If it's nothing major, like .04% here, you're good.

**Comment by kefo** [comment]
Bumping so we don't lose sight of this.  (Obviously for when @RudyOnRails returns.)

**Comment by RudyOnRails** [comment]
@awead my spec was failing on [travis](https://travis-ci.org/aic-collections/aicdams-lakeshore/jobs/358968010#L6033) b/c of no fits.sh. I stubbed the CharacterizeJob class like j-roch [suggested](https://github.com/sciencehistory/chf-sufia/blob/master/spec/features/search_feature_spec.rb#L12-L17):
```
allow_any_instance_of(CharacterizeJob).to receive(:perform).and_return(nil)
```
Is that about all I need? How did you get around fits in the past?

**Comment by awead** [comment]
@RudyOnRails yeah, that should work. I've been stubbing fits for tests.

**Pull request merged**
